// /*
// Copyright © 2025 ESO Maintainer Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

// Copyright External Secrets Inc. All Rights Reserved

// Package ssh implements SSH key generator.
package ssh

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"time"

	"golang.org/x/crypto/ssh"
	apiextensions "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/yaml"

	enterprise "github.com/external-secrets/external-secrets/apis/enterprise/generators/v1alpha1"
	genv1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
)

// Generator implements SSH key generation.
type Generator struct{}

const (
	defaultKeyType = enterprise.SSHKeyTypeRSA
	defaultBits    = 4096

	errNoSpec    = "no config spec provided"
	errParseSpec = "unable to parse spec: %w"
	errGetToken  = "unable to get authorization token: %w"
)

// RSAGenerateFunc is a function type for RSA key generation.
type RSAGenerateFunc func(
	bits int,
) (string, string, error)

// Generate generates SSH key pairs.
func (g *Generator) Generate(_ context.Context, jsonSpec *apiextensions.JSON, _ client.Client, _ string) (map[string][]byte, genv1alpha1.GeneratorProviderState, error) {
	return g.generate(
		jsonSpec,
		generateRSA,
	)
}

// Cleanup cleans up generated SSH keys.
func (g *Generator) Cleanup(_ context.Context, _ *apiextensions.JSON, _ genv1alpha1.GeneratorProviderState, _ client.Client, _ string) error {
	return nil
}

// GetCleanupPolicy returns the cleanup policy for this generator.
func (g *Generator) GetCleanupPolicy(_ *apiextensions.JSON) (*genv1alpha1.CleanupPolicy, error) {
	return nil, nil
}

// LastActivityTime returns the last activity time for generated resources.
func (g *Generator) LastActivityTime(_ context.Context, _ *apiextensions.JSON, _ genv1alpha1.GeneratorProviderState, _ client.Client, _ string) (time.Time, bool, error) {
	return time.Time{}, false, nil
}

// GetKeys returns the keys generated by this generator.
func (g *Generator) GetKeys() map[string]string {
	return map[string]string{
		"id_rsa":     "Private SSH key in PEM format",
		"id_rsa.pub": "Public SSH key in authorized_keys format",
	}
}

func (g *Generator) generate(jsonSpec *apiextensions.JSON, rsaGen RSAGenerateFunc) (map[string][]byte, genv1alpha1.GeneratorProviderState, error) {
	if jsonSpec == nil {
		return nil, nil, errors.New(errNoSpec)
	}
	res, err := parseSpec(jsonSpec.Raw)
	if err != nil {
		return nil, nil, fmt.Errorf(errParseSpec, err)
	}

	keyType := defaultKeyType
	if res.Spec.KeyType != "" {
		keyType = res.Spec.KeyType
	}

	if keyType == enterprise.SSHKeyTypeRSA {
		bits := defaultBits
		if res.Spec.RSAConfig.Bits > 0 {
			bits = res.Spec.RSAConfig.Bits
		}

		privPEM, pubKey, err := rsaGen(bits)
		if err != nil {
			return nil, nil, err
		}
		return map[string][]byte{
			"id_rsa":     []byte(privPEM),
			"id_rsa.pub": []byte(pubKey),
		}, nil, nil
	}
	return nil, nil, fmt.Errorf("unsupported key type: %s", res.Spec.KeyType)
}

func generateRSA(
	bits int,
) (string, string, error) {
	privateKey, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate RSA key: %w", err)
	}

	// Encode private key as PEM
	privDER := x509.MarshalPKCS1PrivateKey(privateKey)
	privPEM := new(bytes.Buffer)
	err = pem.Encode(privPEM, &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: privDER,
	})
	if err != nil {
		return "", "", fmt.Errorf("failed to encode private key: %w", err)
	}

	// Generate public key in authorized_keys format
	pub, err := ssh.NewPublicKey(&privateKey.PublicKey)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate public key: %w", err)
	}
	pubKey := string(ssh.MarshalAuthorizedKey(pub))

	return privPEM.String(), pubKey, nil
}

func parseSpec(data []byte) (*enterprise.SSH, error) {
	var spec enterprise.SSH
	err := yaml.Unmarshal(data, &spec)
	return &spec, err
}

func init() {
	genv1alpha1.Register(enterprise.SSHKind, &Generator{})
	genv1alpha1.RegisterGeneric(enterprise.SSHKind, &enterprise.SSH{})
}
