// Copyright External Secrets Inc. 2025
//
//	All Rights Reserved
package main

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"log"
	"os"
	"text/template"
	"time"

	"github.com/external-secrets/external-secrets/pkg/enterprise/license"
)

const generatedFile = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/license-generator/main.go

package license

const trialLicensePubKey = ` + "`" + `{{.PublicKey}}` + "`" + `

const trialLicenseData = ` + "`" + `
{{.LicenseData}}` + "`" + `

`

func main() {
	// generate a new private key
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		log.Fatalf("failed to generate private key: %v", err)
	}

	// extract public key
	publicKeyBytes, err := x509.MarshalPKIXPublicKey(&privateKey.PublicKey)
	if err != nil {
		log.Fatalf("failed to marshal public key: %v", err)
	}
	publicKeyPem := pem.EncodeToMemory(&pem.Block{
		Type:  "PUBLIC KEY",
		Bytes: publicKeyBytes,
	})
	subs := []license.LicenseSubscription{}
	// create license data
	subs = append(subs, workflowTrial...)
	subs = append(subs, federationTrial...)
	subs = append(subs, scanTrial...)
	subs = append(subs, targetsTrial...)
	subs = append(subs, generatorTrial...)

	// generate license
	generatedLicense, err := license.GenerateLicense(privateKey, licData, subs)
	if err != nil {
		log.Fatalf("failed to generate license: %v", err)
	}

	// create template data
	tmplData := struct {
		PublicKey   string
		LicenseData string
	}{
		PublicKey:   string(publicKeyPem),
		LicenseData: string(generatedLicense),
	}

	// parse template
	tmpl, err := template.New("license").Parse(generatedFile)
	if err != nil {
		log.Fatalf("failed to parse template: %v", err)
	}

	// execute template
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, tmplData); err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}

	// write to file
	if err := os.WriteFile("zz_keys_generated.go", buf.Bytes(), 0600); err != nil {
		log.Fatalf("failed to write generated file: %v", err)
	}

	fmt.Println("Successfully generated trial license keys.")
}

var date = time.Now()
var licData = license.LicenseData{
	LicenseID:      "trial-license",
	CustomerName:   "trial",
	IssueDate:      date,
	ExpirationDate: date.AddDate(0, 1, 0),
	Version:        "trial",
}

var workflowTrial = []license.LicenseSubscription{
	{
		Name:       "workflow.core",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "workflow.run",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "workflow.run.template",
		ExpiryDate: date.String(),
		MaxLimit:   3,
	},
	{
		Name:       "workflow.template",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
}

var federationTrial = []license.LicenseSubscription{}

var scanTrial = []license.LicenseSubscription{}

var targetsTrial = []license.LicenseSubscription{}

var generatorTrial = []license.LicenseSubscription{
	{
		Name:       "generator.aws_iam",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.basic_auth",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.postgresql",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.federation",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.mongodb",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.rabbitmq",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.neo4j",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.openai",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.ssh",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
	{
		Name:       "generator.sendgrid",
		ExpiryDate: date.String(),
		MaxLimit:   0,
	},
}
