//go:build !ignore_autogenerated

/*
Copyright © 2025 ESO Maintainer Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package enterprise

import (
	"github.com/external-secrets/external-secrets/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsAuth) DeepCopyInto(out *ExternalSecretsAuth) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(ExternalSecretsKubernetesAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsAuth.
func (in *ExternalSecretsAuth) DeepCopy() *ExternalSecretsAuth {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsCARef) DeepCopyInto(out *ExternalSecretsCARef) {
	*out = *in
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsCARef.
func (in *ExternalSecretsCARef) DeepCopy() *ExternalSecretsCARef {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsCARef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsKubernetesAuth) DeepCopyInto(out *ExternalSecretsKubernetesAuth) {
	*out = *in
	in.ServiceAccountRef.DeepCopyInto(&out.ServiceAccountRef)
	in.CaCertRef.DeepCopyInto(&out.CaCertRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsKubernetesAuth.
func (in *ExternalSecretsKubernetesAuth) DeepCopy() *ExternalSecretsKubernetesAuth {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsKubernetesAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsProvider) DeepCopyInto(out *ExternalSecretsProvider) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	in.Auth.DeepCopyInto(&out.Auth)
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsProvider.
func (in *ExternalSecretsProvider) DeepCopy() *ExternalSecretsProvider {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsServer) DeepCopyInto(out *ExternalSecretsServer) {
	*out = *in
	if in.CaRef != nil {
		in, out := &in.CaRef, &out.CaRef
		*out = new(ExternalSecretsCARef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsServer.
func (in *ExternalSecretsServer) DeepCopy() *ExternalSecretsServer {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsTarget) DeepCopyInto(out *ExternalSecretsTarget) {
	*out = *in
	if in.ClusterSecretStoreName != nil {
		in, out := &in.ClusterSecretStoreName, &out.ClusterSecretStoreName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsTarget.
func (in *ExternalSecretsTarget) DeepCopy() *ExternalSecretsTarget {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsTarget)
	in.DeepCopyInto(out)
	return out
}
