apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fake-test
  namespace: default
spec:
  refreshInterval: 1h
  # A SecretStore reference is required but not used when using a generator
  secretStoreRef:
    name: dummy
    kind: SecretStore
  # Reference the Fake generator
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: test-fake-generator
---
# Dummy SecretStore (required but not used)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dummy
  namespace: default
spec:
  provider:
    fake:
      data: []
