// /*
// Copyright © 2025 ESO Maintainer Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

//go:build !ignore_autogenerated
// Code generated by generator_impl_gen.go; DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"reflect"

	genv1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
	apiextensions "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ genv1alpha1.GenericGenerator = &AWSIAMKey{}

func (g *AWSIAMKey) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *AWSIAMKey) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *AWSIAMKey) GetKind() string {
	return reflect.TypeOf(AWSIAMKey{}).Name()
}

func (g *AWSIAMKey) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *AWSIAMKey) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &BasicAuth{}

func (g *BasicAuth) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *BasicAuth) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *BasicAuth) GetKind() string {
	return reflect.TypeOf(BasicAuth{}).Name()
}

func (g *BasicAuth) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *BasicAuth) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &Federation{}

func (g *Federation) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *Federation) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *Federation) GetKind() string {
	return reflect.TypeOf(Federation{}).Name()
}

func (g *Federation) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *Federation) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &MongoDB{}

func (g *MongoDB) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *MongoDB) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *MongoDB) GetKind() string {
	return reflect.TypeOf(MongoDB{}).Name()
}

func (g *MongoDB) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *MongoDB) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &Neo4j{}

func (g *Neo4j) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *Neo4j) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *Neo4j) GetKind() string {
	return reflect.TypeOf(Neo4j{}).Name()
}

func (g *Neo4j) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *Neo4j) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &OpenAI{}

func (g *OpenAI) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *OpenAI) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *OpenAI) GetKind() string {
	return reflect.TypeOf(OpenAI{}).Name()
}

func (g *OpenAI) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *OpenAI) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &PostgreSQL{}

func (g *PostgreSQL) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *PostgreSQL) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *PostgreSQL) GetKind() string {
	return reflect.TypeOf(PostgreSQL{}).Name()
}

func (g *PostgreSQL) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *PostgreSQL) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &RabbitMQ{}

func (g *RabbitMQ) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *RabbitMQ) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *RabbitMQ) GetKind() string {
	return reflect.TypeOf(RabbitMQ{}).Name()
}

func (g *RabbitMQ) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *RabbitMQ) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &SSH{}

func (g *SSH) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *SSH) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *SSH) GetKind() string {
	return reflect.TypeOf(SSH{}).Name()
}

func (g *SSH) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *SSH) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}

var _ genv1alpha1.GenericGenerator = &SendgridAuthorizationToken{}

func (g *SendgridAuthorizationToken) GetObjectMeta() *metav1.ObjectMeta {
	return &g.ObjectMeta
}

func (g *SendgridAuthorizationToken) GetTypeMeta() *metav1.TypeMeta {
	return &g.TypeMeta
}

func (g *SendgridAuthorizationToken) GetKind() string {
	return reflect.TypeOf(SendgridAuthorizationToken{}).Name()
}

func (g *SendgridAuthorizationToken) SetOutputs(expectedOutput map[string]string) error {
	bytes, err := json.Marshal(expectedOutput)
	if err != nil {
		return err
	}

	g.Status.Output = &apiextensions.JSON{
		Raw: bytes,
	}
	return nil
}

func (g *SendgridAuthorizationToken) Copy() genv1alpha1.GenericGenerator {
	return g.DeepCopy()
}
