apiVersion: federation.external-secrets.io/v1alpha1
kind: Authorization
metadata:
  name: test-authorization
spec:
  federationRef:
    name: test-federation
    kind: Kubernetes
  subject:
    subject: "system:serviceaccount:default:default"
    issuer: "kubernetes.default.svc"
  allowedClusterSecretStores:
    - "default"
  allowedGenerators:
    - name: test-password
      kind: Password
      namespace: default
  allowedGeneratorStates:
    - namespace: default
