apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-test
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dummy
    kind: SecretStore
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Federation
          name: test-federation-generator
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dummy
  namespace: default
spec:
  provider:
    fake:
      data: []