apiVersion: generators.external-secrets.io/v1alpha1
kind: Federation
metadata:
  name: test-federation-generator
  namespace: default
spec:
  server:
    url: "http://external-secrets-webhook.external-secrets.svc.cluster.local:8000"
  generator:
    namespace: default
    kind: Password
    name: test-password
  auth:
    tokenSecretRef:
      name: federation-auth
      key: token