apiVersion: v1
kind: Secret
metadata:
  name: federation-auth
  namespace: default
type: Opaque
stringData:
  token: "eyJhbGciOiJSUzI1NiIsImtpZCI6InRlc3Qta2lkIn0.eyJpc3MiOiJrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6ZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoiZGVmYXVsdCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJkZWZhdWx0IiwidWlkIjoidGVzdC11aWQifX19.ZmFrZXNpZ25hdHVyZQ"
