apiVersion: federation.external-secrets.io/v1alpha1
kind: Authorization
metadata:
  name: test-federation-auth
spec:
  federationRef:
    kind: "Kubernetes"
    name: "test-k8s-federation"
  subject:
    issuer: "https://kubernetes.default.svc.cluster.local"
    subject: "system:serviceaccount:test-federation:test-federation-sa"
  allowedClusterSecretStores:
    - "test-cluster-store"
  allowedGenerators:
    - name: "test-cluster-gen"
      kind: "ClusterGenerator"
      namespace: "test-federation"
  allowedGeneratorStates:
    - namespace: "test-federation"