apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-secret-store-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-secret-store-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-secret-store-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-secret-store-role
subjects:
- kind: ServiceAccount
  name: test-secret-store-sa
  namespace: default
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: test-cluster-store
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc.cluster.local"
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
          namespace: "kube-system"
      auth:
        serviceAccount:
          name: "test-secret-store-sa"
          namespace: "default"
      remoteNamespace: "test-federation"