apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federated-secret
  namespace: federation-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: federation-secret-store
    kind: ClusterSecretStore
  target:
    name: synced-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: source-secret
        property: username
    - secretKey: password
      remoteRef:
        key: source-secret
        property: password
