apiVersion: federation.external-secrets.io/v1alpha1
kind: Authorization
metadata:
  name: test-authorization
spec:
  federationRef:
    name: test-federation
    kind: Kubernetes
  subject:
    subject: "system:serviceaccount:your-namespace:federation-sa"
    issuer: "kubernetes.default.svc"
  allowedClusterSecretStores:
    - "default"
  allowedGenerators:
    - name: password-gen
      kind: Password
      namespace: default
